name: Build and Release for Windows

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Create .env file
    - name: Create .env file
      run: |
        echo "VITE_SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
        echo "VITE_APTABASE_APP_ID=${{ secrets.APTABASE_APP_ID }}" >> .env

    # Build and publish the Electron app
    - name: Build and publish Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run build:win
        npm run publish
